export const CREATE_SCHOLARSHIP_REQUEST = 'CREATE_SCHOLARSHIP_REQUEST';
export const CREATE_SCHOLARSHIP_SUCCESS = 'CREATE_SCHOLARSHIP_SUCCESS';
export const CREATE_SCHOLARSHIP_FAILURE = 'CREATE_SCHOLARSHIP_FAILURE';

export const GET_SCHOLARSHIPS_REQUEST = 'GET_SCHOLARSHIPS_REQUEST';
export const GET_SCHOLARSHIPS_SUCCESS = 'GET_SCHOLARSHIPS_SUCCESS';
export const GET_SCHOLARSHIPS_FAILURE = 'GET_SCHOLARSHIPS_FAILURE';

export const GET_SINGLE_SCHOLARSHIP_REQUEST = 'GET_SINGLE_SCHOLARSHIP_REQUEST';
export const GET_SINGLE_SCHOLARSHIP_SUCCESS = 'GET_SINGLE_SCHOLARSHIP_SUCCESS';
export const GET_SINGLE_SCHOLARSHIP_FAILURE = 'GET_SINGLE_SCHOLARSHIP_FAILURE';

export const SUPPORT_SCHOLARSHIP_REQUEST = 'SUPPORT_SCHOLARSHIP_REQUEST';
export const SUPPORT_SCHOLARSHIP_SUCCESS = 'SUPPORT_SCHOLARSHIP_SUCCESS';
export const SUPPORT_SCHOLARSHIP_FAILURE = 'SUPPORT_SCHOLARSHIP_FAILURE';
